apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app
  namespace: chores
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: chores
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      volumes:
        - name: data
          nfs:
            path: /mnt/scratch/farm/chores
            server: archive.local
      containers:
      - name: app
        image: arecker/chores:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: data
          mountPath: /usr/src/app/data
