apiVersion: apps/v1
kind: Deployment
metadata:
  name: chores
  namespace: chores
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: chores
  template:
    metadata:
      labels:
        name: chores
    spec:
      securityContext:
        runAsUser: 1026
        runAsGroup: 1001
      volumes:
        - name: data
          nfs:
            path: /volume1/farm/chores
            server: nas.local
      containers:
      - name: app
        image: arecker/chores:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: data
          mountPath: /usr/src/app/data
