---
apiVersion: v1
kind: Service
metadata:
  name: chores
  namespace: chores
spec:
  ports:
  - protocol: TCP
    port: 5000
  selector:
    service: chores
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: chores
  namespace: chores
spec:
  rules:
  - host: chores.local
    http:
      paths:
      - backend:
          serviceName: chores
          servicePort: 5000
